// Concatenates schema/*.sql into one deploy script per target.
//
//   node deploy/build.mjs            -> deploy/ibid.sql (plain Postgres)
//   node deploy/build.mjs supabase   -> deploy/ibid-supabase.sql
//
// schema/ stays search-path agnostic so the PGlite suite runs it unchanged.
// The Supabase target wraps every object in a private `ibid` schema and
// appends deploy/supabase.sql (hardening: pinned search paths, no Data API
// path into the private schema, the `api` surface). Both outputs are
// generated and gitignored; the schema/ files are the source.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const target = process.argv[2] ?? 'postgres';
const files = fs.readdirSync(path.join(root, 'schema')).filter((f) => /^\d{3}_.*\.sql$/.test(f)).sort();
const body = files.map((f) => `-- ---- schema/${f}\n${fs.readFileSync(path.join(root, 'schema', f), 'utf8')}`).join('\n\n');

let out;
if (target === 'postgres') {
  out = ['-- GENERATED by deploy/build.mjs from schema/. Do not edit.', body].join('\n\n');
} else if (target === 'supabase') {
  const hardeningPath = path.join(root, 'deploy', 'supabase.sql');
  const hardening = fs.existsSync(hardeningPath) ? fs.readFileSync(hardeningPath, 'utf8') : '-- deploy/supabase.sql not written yet';
  out = ['-- GENERATED by deploy/build.mjs from schema/ + deploy/supabase.sql. Do not edit.',
    'create schema if not exists ibid;', 'set search_path = ibid, pg_catalog;',
    body.replace(/schema public/g, 'schema ibid'), hardening].join('\n\n');
} else {
  throw new Error(`unknown target ${target}`);
}
const dest = path.join(root, 'deploy', target === 'postgres' ? 'ibid.sql' : 'ibid-supabase.sql');
fs.writeFileSync(dest, out);
console.log(`${path.relative(root, dest)} written, ${files.length} file(s), ${out.length} bytes`);
